#!/bin/bash

function timer_start {
    timer=${timer:-$SECONDS}
}
function timer_stop {
    timer_show=$(($SECONDS - $timer))
    if [ $timer_show -eq 0 ];then timer_show=''; else timer_show+='s ';fi
    unset timer
}
trap 'timer_start' DEBUG
PROMPT_COMMAND=timer_stop
PS1="\$? \[\033[0;33m\]\${timer_show}\[\`if [[ \$? = "0" ]]; then echo '\e[36m'; else echo '\e[31m' ; fi\`\]\W> \[\e[m\]"

